{% set name = "CTDopts" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WorkflowConversion/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0162fc066555f8f82dbb47a285393c58c864b1fcf549eacabba9e16b2dec9f73

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - CTDopts

about:
  home: https://github.com/WorkflowConversion/CTDopts
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: module for CTD handling
  description: |
    CTDopts is a module for enabling tools with CTD reading/writing,
    argument parsing, validating and manipulating capabilities.

extra:
  recipe-maintainers:
    - bernt-matthias
