{% set name = "CTDopts" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WorkflowConversion/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 39f6076e6af9f02face2d1df0b771bb5464e560b90da04fe67d8f2916eed0bb1

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - CTDopts

about:
  home: https://github.com/WorkflowConversion/CTDopts
  license: GPL
  license_family: GPL
  license_file: LICENSE
  summary: 'module for CTD handling'
  description: |
    CTDopts is a module for enabling tools with CTD reading/writing,
    argument parsing, validating and manipulating capabilities.

extra:
  recipe-maintainers:
    - bernt-matthias
